In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('img_measurements.csv',index_col=0)

In [3]:
#start by aggregating the nucleoli together
dfavg=df.groupby('nuclear_id').agg('mean')

In [4]:
dfavg.head()

,id,nuclear_area,nuclear_avg,nuclear_stdev,number_nucleoli,nucleolar_area,nucleolar_avg,nucleolar_stdev,third_nucavg,third_nucstdev,third_nuclavg,third_nuclstdev
nuclear_id,,,,,,,,,,,,
1,0.5,2410.0,1522.423268,1455.759119,2.0,80.5,5697.907342,1191.592678,1296.417575,2285.924745,7756.871166,1767.602840
2,4.0,3006.0,1556.982159,1696.827323,5.0,30.0,7315.438852,1439.814964,1403.773721,2337.835445,8648.766109,1581.897730
3,8.0,2534.0,1465.758567,1284.615167,3.0,34.0,5889.262202,893.705719,1074.074521,1620.456095,6531.376343,1060.248498
4,11.5,2084.0,1966.867648,1477.533833,4.0,57.0,5146.195512,850.748443,2083.068963,2916.697730,8029.232959,1495.104706
5,16.0,2259.0,2145.047947,1920.534223,5.0,40.8,6872.403584,1295.650714,1991.653550,3279.893963,10059.272797,2179.338041

In [5]:
#now calculate the stats
dfavg['int_nucleolar']=dfavg['nucleolar_avg']*dfavg['nucleolar_area']*dfavg['number_nucleoli']
dfavg['int_nucleoplasm']=dfavg['nuclear_area']*dfavg['nuclear_avg']-dfavg['int_nucleolar']
dfavg['nucleolar_enrich']=dfavg['int_nucleolar']/dfavg['int_nucleoplasm']
dfavg['third_intnucl']=dfavg['third_nuclavg']*dfavg['nucleolar_area']*dfavg['number_nucleoli']
dfavg['third_intnucp']=dfavg['nuclear_area']*dfavg['third_nucavg']-dfavg['third_intnucl']
dfavg['third_nuclenrich']=dfavg['third_intnucl']/dfavg['third_intnucp']
dfavg['normality_score']=dfavg['third_nuclenrich']/dfavg['nucleolar_enrich']

In [6]:
dfavg.head()

,id,nuclear_area,nuclear_avg,nuclear_stdev,number_nucleoli,nucleolar_area,nucleolar_avg,nucleolar_stdev,third_nucavg,third_nucstdev,third_nuclavg,third_nuclstdev,int_nucleolar,int_nucleoplasm,nucleolar_enrich,third_intnucl,third_intnucp,third_nuclenrich,normality_score
nuclear_id,,,,,,,,,,,,,,,,,,,
1,0.5,2410.0,1522.423268,1455.759119,2.0,80.5,5697.907342,1191.592678,1296.417575,2285.924745,7756.871166,1767.602840,9.173631e+05,2.751677e+06,0.333383,1.248856e+06,1.875510e+06,0.665876,1.997327
2,4.0,3006.0,1556.982159,1696.827323,5.0,30.0,7315.438852,1439.814964,1403.773721,2337.835445,8648.766109,1581.897730,1.097316e+06,3.582973e+06,0.306259,1.297315e+06,2.922429e+06,0.443917,1.449484
3,8.0,2534.0,1465.758567,1284.615167,3.0,34.0,5889.262202,893.705719,1074.074521,1620.456095,6531.376343,1060.248498,6.007047e+05,3.113527e+06,0.192934,6.662004e+05,2.055504e+06,0.324106,1.679879
4,11.5,2084.0,1966.867648,1477.533833,4.0,57.0,5146.195512,850.748443,2083.068963,2916.697730,8029.232959,1495.104706,1.173333e+06,2.925620e+06,0.401054,1.830665e+06,2.510451e+06,0.729218,1.818251
5,16.0,2259.0,2145.047947,1920.534223,5.0,40.8,6872.403584,1295.650714,1991.653550,3279.893963,10059.272797,2179.338041,1.401970e+06,3.443693e+06,0.407112,2.052092e+06,2.447054e+06,0.838597,2.059865

In [7]:
dfavg.to_csv('img_measurements_normality.csv')